//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paycor.Import {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ImportResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ImportResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Paycor.Import.ImportResource", typeof(ImportResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid upload file..
        /// </summary>
        public static string FileUploadInvalidFile {
            get {
                return ResourceManager.GetString("FileUploadInvalidFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file upload message could not be cast to an employee import file upload message..
        /// </summary>
        public static string FileUploadMessageNull {
            get {
                return ResourceManager.GetString("FileUploadMessageNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing ApiEndpoint which is required for export payload..
        /// </summary>
        public static string ImportMissingApiEndpoint {
            get {
                return ResourceManager.GetString("ImportMissingApiEndpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify the BaseAddress={0} configuration value has been set in the configuration being used..
        /// </summary>
        public static string ImportMissingBaseAddressConfigurationSettings {
            get {
                return ResourceManager.GetString("ImportMissingBaseAddressConfigurationSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify the BaseAddress={0}, ApiEndpoint={1} configuration values have been set in the configuration being used..
        /// </summary>
        public static string ImportMissingConfigurationSettings {
            get {
                return ResourceManager.GetString("ImportMissingConfigurationSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing records which is required for export payload..
        /// </summary>
        public static string ImportMissingRecords {
            get {
                return ResourceManager.GetString("ImportMissingRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected content is not present in response..
        /// </summary>
        public static string ImportNoResponseContent {
            get {
                return ResourceManager.GetString("ImportNoResponseContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The system was unable to authorize the current import operation..
        /// </summary>
        public static string ImportServiceAuthenticationFailure {
            get {
                return ResourceManager.GetString("ImportServiceAuthenticationFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected response was received from the server..
        /// </summary>
        public static string ImportServiceResponseUnexpected {
            get {
                return ResourceManager.GetString("ImportServiceResponseUnexpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected response was received from the server with a message of {1}..
        /// </summary>
        public static string ImportServiceResponseUnexpectedWithMsg {
            get {
                return ResourceManager.GetString("ImportServiceResponseUnexpectedWithMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An import request to the target system either timed out or the system was unresponsive..
        /// </summary>
        public static string ImportServiceUnresponsive {
            get {
                return ResourceManager.GetString("ImportServiceUnresponsive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem with the import in progress and processing cannot continue..
        /// </summary>
        public static string ProcessingException {
            get {
                return ResourceManager.GetString("ProcessingException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This item does not exist or has already been removed from the system..
        /// </summary>
        public static string ResourceAlreadyRemoved {
            get {
                return ResourceManager.GetString("ResourceAlreadyRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested item was not found in the system..
        /// </summary>
        public static string ResourceNotFound {
            get {
                return ResourceManager.GetString("ResourceNotFound", resourceCulture);
            }
        }
    }
}
